// RootLayout.tsx
// このファイルは Next.js アプリ全体のルートレイアウトを定義する。
// 共通の HTML 構造、グローバルスタイル、フォント設定、およびメタデータを提供する。
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Sound Level Meter',
  description: 'Generated by KoenigWolf',
};

// RootLayout コンポーネント
// このコンポーネントは、全ページに共通する HTML のラッパーとして機能する。
// 各ページコンテンツは {children} としてレンダリングされる。
export default function RootLayout({
  children,
}: {
  // children は React のノード型を受け取る
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      {/* body 要素には、Inter フォントのクラスを適用 */}
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
